### ISSUE TITLE
ST7789_lib_Numeric_display shows stack smash in showVal 

### ISSUE THREAD

**Issue by donwade** [cbm80amiga/ST7789_AVR#1]
Retargeted for esp32. This was detected by a trapped backtrace.
char txt[10] too small increased to char txt[25] and stack smash went away.
Could be a smaller allocation but I don't have enough time to find the best value cause I don't know what this obtusely written function does.

**Comment by cbm80amiga** [comment]
Thank you for noticing it. Already fixed it - txt buffer should have length of w+1
