### ISSUE TITLE
ST7789 (240*240) gives a blurry vertical lines with Arduino pro micro!

### ISSUE THREAD

**Issue by HMI1973** [cbm80amiga/ST7789_AVR#2]
I'm working on ST7789 (240*240) from Aliexpress without CS pin, I used Arduino Pro Micro but actually the screen doesn't show the text nor the graphics correctly, it gives a kind of blurry vertical lines. 

I enabled "**COMPATIBILITY_MODE**" in "**ST7789_AVR.h**" to use SPI instead of assembly "NOP" Approach, this should ensure the code compatible with all Arduino boards.

**ST7789 Wiring :**
![wiring](https://github.com/user-attachments/assets/e4cdd7ff-5007-4ca5-bed1-a30d89feb08b)

What I get is a blurry result:
![ST7789](https://github.com/user-attachments/assets/f92da776-dcf6-4e6e-b0fd-e93a19a99ccc)

I'm trying to investigate the case but anyone faced this issue before?
**Code:**
```c++
#include "src/ST7789_AVR.h"

#define TFT_CS  -1 // without CS
#define TFT_RST  8
#define TFT_DC   9

#define SCR_WD 240
#define SCR_HT 240

ST7789_AVR lcd = ST7789_AVR(TFT_DC, TFT_RST, TFT_CS);
int xx=0;

void setup(void) 
{
	delay(2000);
	Serial.begin(115200);
	lcd.init(SCR_WD, SCR_HT);
	lcd.fillScreen(BLACK);
	lcd.fillScreen(BLUE);
}

void loop()
{
	xx=(xx+1)%40;
	lcd.setCursor(xx, 10);
	lcd.setTextColor(WHITE,BLUE);
	lcd.setTextSize(2);
	lcd.println("HELLO WORLD");
}
```

**Comment by HMI1973** [comment]
After investigation i found the module is damaged when i changed it it work fine!

**Comment by cbm80amiga** [comment]
Good to know :)

**Comment by Romacat2** [comment]
Most likely, this is due to the wrong logic level and power level. Such displays mostly operate at 3.3V, not 5V like Arduino Uno/Nano/Mega.
