### ISSUE TITLE
Addition of new supported displays and new artificial horizons

### ISSUE THREAD

**Issue by brightproject** [cbm80amiga/ST7789_AVR#3]
Hello @cbm80amiga 
I am interested in the topic of artificial horizons, when you announced a fast `artificial horizon`, I became interested in trying it on a larger screen, for example `240x320` on the controller `ILI9341`
The [example](https://github.com/cbm80amiga/ST7789_AVR/blob/main/examples/ST7789_Artificial_Horizon/ST7789_Artificial_Horizon.ino) is available in the simulator, I also want to try it on real hardware.

> https://wokwi.com/projects/406585521751027713

I managed to use your [library](https://github.com/cbm80amiga/ILI9341_Fast) for this display.
But isolated artifacts are confusing, maybe this is a discrepancy with the original display size for which you wrote the code?

![Скриншот 18-08-2024 22 37 28](https://github.com/user-attachments/assets/5b03dea3-86eb-4f13-8e95-7873e3ef0c6c)

Perhaps you will be interested in other artificial horizons that I periodically find and improve.

> https://wokwi.com/projects/406500228582797313
> https://wokwi.com/projects/406507609488531457

https://github.com/Bodmer/TFT_eSPI/assets/1788098/42e47b1b-0d4a-4be8-bfde-b1f82b53999e

> https://wokwi.com/projects/374062283976666113

and one interesting code, still in static form.

> https://wokwi.com/projects/375745332267555841

It would be great if you optimized and improved some of them for displays `ILI9341`, `SSD1306` or `ST7701`.
I would be glad to have an interesting discussion.

**Comment by cbm80amiga** [comment]
Unfortunately AVR Arduinos are too slow for more complex graphics rendered in real-time
And no actual frame buffer in MCU's RAM doesn't help too :)
Regarding your issues it seems to be simple - SCR_HT and SCT_WD should be the same and not greater than 255 because all buffers use 8-bit data. This demo is rather limited to square screens or at least square part of the display can be used.
