### ISSUE TITLE
TFT_MOSI and TFT_SCLK

### ISSUE THREAD

**Issue by step135** [cbm80amiga/ST7789_AVR#4]
I want to use it on ESP32 CAM and I am not able to define those pins.

**Comment by cbm80amiga** [comment]
This library is optimized for AVR chips. But in compatiblity mode it uses regular Arduino hardware SPI library, so maybe it will work in such mode on ESP32.

**Comment by step135** [comment]
I am not asking if it will work or not. My question was where to define those pins.

**Comment by cbm80amiga** [comment]
AVR Arduino has only 1 hardware SPI and you cannot define any MOSI/MISO/SCLK pins. STM32 has 2 SPIs but you cannot define pins, too. I don't know how it is solved in ESP32, check documentation to SPI library for this MCU. But I think it will be easier to use other library for ESP32 or ESP8266, I believe there are a few of them supporting most LCD controllers.
